function [fitresult, gof] = createFitMachCNa(mach_axis, cna_axis_1)
%CREATEFIT(MACH_AXIS,CNA_AXIS_1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: mach_axis
%      Y Output: cna_axis_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Mar-2025 14:26:43


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( mach_axis, cna_axis_1 );

% Set up fittype and options.
ft = fittype( 'fourier5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 1.0530228896871];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cna_axis_1 vs. mach_axis', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'mach_axis', 'Interpreter', 'none' );
ylabel( 'cna_axis_1', 'Interpreter', 'none' );
grid on


