function [fitresult, gof] = createFitAoACNa(aoa_axis, cna_axis_2)
%CREATEFIT(AOA_AXIS,CNA_AXIS_2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: aoa_axis
%      Y Output: cna_axis_2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Mar-2025 14:29:57


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( aoa_axis, cna_axis_2 );

% Set up fittype and options.
ft = fittype( 'fourier2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0.0181028148106015];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cna_axis_2 vs. aoa_axis', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'aoa_axis', 'Interpreter', 'none' );
ylabel( 'cna_axis_2', 'Interpreter', 'none' );
grid on


